### ISSUE TITLE
Revamp UI

### ISSUE THREAD

**Issue by jjingrong** [CS2103JAN2017-F12-B2/main#17]

**Comment by jjingrong** [comment]
### Progressive changes

- [x] Change to better cells #32
- [x] Change color scheme #33
- [ ] Add some graphics #34
- [ ] Overhaul UI (Differentiating factor)

**Comment by jjingrong** [comment]
Feature dropped
